package automaticpaper;

import static automaticpaper.Login1_1.jobs;
import static automaticpaper.Login1_1.sourceCode;
import static automaticpaper.rssFeeder.readRss;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.DefaultCaret;

public class Login1 extends javax.swing.JFrame {
public static String username1;
 public static String sourceCode="";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    static String pwd=null;
    public static String uname = null;
    //String user1=null;
    //private jframe frame;
    //  private Login1 frame;

    /**
     *
     */
    public Login1() {
        setContentPane(new JLabel(new ImageIcon("C://Users//Joyan//Desktop//11.jpg")));
        initComponents();
        //this.setLocation(500,500);
       /* Random gen = new Random();

        Color color = new Color(gen.nextInt(240), gen.nextInt(240),
                gen.nextInt(240));
        this.getContentPane().setBackground(color);*/
        this.setTitle("LOGIN");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void close() {
        WindowEvent WinClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WinClosingEvent);
    }

    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        news = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newname = new javax.swing.JTextArea();
        LINK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 0, 400, 100));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOG IN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 10), new java.awt.Color(102, 0, 255))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setText("Username:"); // NOI18N

        login.setText("LogIn");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel2.setText("password:");

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        register.setText("New User");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(login)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(txt_password)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(register)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(register))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 270, 423, 159);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(32, 116, 0, 159);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 30, 919, 65);

        news.setText("Job News");
        news.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsActionPerformed(evt);
            }
        });
        getContentPane().add(news);
        news.setBounds(760, 180, 130, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automaticpaper/images.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 230, 220);

        newname.setColumns(20);
        newname.setRows(5);
        jScrollPane1.setViewportView(newname);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 216, 500, 280);

        LINK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(LINK);
        LINK.setBounds(570, 510, 500, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("LINK");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(530, 510, 30, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csv_db", "root", "");
 
            //frame= new Login1();
        } catch (SQLException ex) {
            Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    @SuppressWarnings("empty-statement")
    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
    }//GEN-LAST:event_loginMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String sql = "select * from login where username=? AND Password=?";
       
        // TODO add your handling code here:
        try {

            pst = con.prepareStatement(sql);
                // pst = con.prepareStatement(sql1);
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());
            rs = pst.executeQuery();
            pwd=txt_password.getText();
            int count = 0;
           // System.out.println(sql1);
            uname = txt_username.getText();
            //System.out.println(user);
            String password=txt_password.getText();
                    //composer4.username1=user;
            //GlobalVars.addValuesToGlobalMap("username", user);

            if (rs.next()) {
                // System.out.println(count);
                // count=count+1;
                //System.out.println(count);

             //   JOptionPane.showMessageDialog(null, "username and password is correct");
                // frame.dispose();
                // System.out.println(count);
                //frame.dispose();
                this.dispose();

                composer4 c = new composer4();
                c.setVisible(true);

                //Paper_info s= new Paper_info();
                //s.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null,"Invalid username and password");
            }
            register r = new register();
           // Profile profile = new Profile();
           // Profile.name.setText("ABC");
          // Profile.name.setEnabled(false);
//          Profile.qualification.setText(this.qualification1.getText());
           // Profile.qualification.setEnabled(true);
//            Profile.phone.setText(this.phone1.getText());
           // Profile.phone.setEnabled(true);
            //        Profile.research.setText(this.research1.getText());
           // Profile.research.setEnabled(true);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        register register = new register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerActionPerformed
public static String readRss(String urlAddress) throws IOException {
        try{
        URL rssUrl=new URL(urlAddress);
        BufferedReader in=new BufferedReader(new InputStreamReader(rssUrl.openStream()));
       int count=0;
        String line;
        while ((line = in.readLine()) != null ) {
    int titleEndIndex = 0;
    int titleStartIndex = 0;
    while (titleStartIndex >= 0&& count!=10) {
        titleStartIndex = line.indexOf("<title>", titleEndIndex);
        if (titleStartIndex >= 0) {
            titleEndIndex = line.indexOf("</title>", titleStartIndex);
              System.out.println();
            sourceCode += line.substring(titleStartIndex + "<title>".length(), titleEndIndex) + "\n";
           // count++;
           // System.out.println(count);
          
            
        }
    }
}
        
       /* while((line = in.readLine())!= null)
        {
            
            if(line.contains("<title>"))
            {
            int firstPos = line.indexOf("<title>");
            String temp = line.substring(firstPos);
            temp = temp.replace("<title>", "");
            int lastPos = temp.indexOf("</title>");
            temp = temp.substring(0, lastPos);
            sourceCode += temp+"\n";
            }
        }*/
        
       /* while((line = in.readLine())!= null)
        {
            if(line.contains("<title>"))
            {
                
                int firstPos = line.indexOf("<title>");
                String temp = line.substring(firstPos);
                int fp = temp.indexOf("</title>");
                int lastPos = line.indexOf("</title>");
                
            System.out.println(firstPos);
            System.out.println(lastPos);
            System.out.println(fp);
            }    
        
        }*/  
       in.close();
       
        return sourceCode;
        
    }catch(MalformedURLException e){
        System.out.println("Something went wrong reading URL");
    }
        catch(IOException e){
            System.out.println("hello");
        }
        
        /*if (sourceCode.contains(",")) {
                    jobs = sourceCode.split(",");
        }
       
        System.out.println(jobs.length);
        for(int i=2;i<jobs.length;i++){
         System.out.println(jobs[i]);
        
        }*/
    //catch(MalFormedURLException e){
        //System.out.println("MalFormed URL");
    //}

    return null;
    }
    private void newsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsActionPerformed
                newname.setText(sourceCode);  
              LINK.setText("http://www.careerbuilder.com/");
                System.out.println();
              // newname.setText("LINK:-http://www.careerbuilder.com/RTQ/rss20.aspx?rssid=RSS_PD&num=25&geoip=false&ddcompany=false&ddtitle=false&cat=JN004");
       /* try{
     //   URL rssUrl=new URL("http://www.careerbuilder.com/RTQ/rss20.aspx?rssid=RSS_PD&num=25&geoip=false&ddcompany=false&ddtitle=false&cat=JN004");
       // BufferedReader in=new BufferedReader(new InputStreamReader(rssUrl.openStream()));
       
        String line;
        while ((line = in.readLine()) != null) {
    int titleEndIndex = 0;
    int titleStartIndex = 0;
    
    while (titleStartIndex >= 0) {
        titleStartIndex = line.indexOf("<title>", titleEndIndex);
        if (titleStartIndex >= 0) {
            titleEndIndex = line.indexOf("</title>", titleStartIndex);
            sourceCode += line.substring(titleStartIndex + "<title>".length(), titleEndIndex);
           
          
            newname.setText(sourceCode);
            System.out.println();
        }
    }
}
        /*
           if (sourceCode.contains(",")) {
                    jobs = sourceCode.split(",");
        }
       
        System.out.println(jobs.length);
        for(int i=2;i<jobs.length;i++){
         System.out.println(jobs[i]);   
        
        }*/
       /* while((line = in.readLine())!= null)
        {
            
            if(line.contains("<title>"))
            {
            int firstPos = line.indexOf("<title>");
            String temp = line.substring(firstPos);
            temp = temp.replace("<title>", "");
            int lastPos = temp.indexOf("</title>");
            temp = temp.substring(0, lastPos);
            sourceCode += temp+"\n";
            }
        }*/
        
       /* while((line = in.readLine())!= null)
        {
            if(line.contains("<title>"))
            {
                
                int firstPos = line.indexOf("<title>");
                String temp = line.substring(firstPos);
                int fp = temp.indexOf("</title>");
                int lastPos = line.indexOf("</title>");
                
            System.out.println(firstPos);
            System.out.println(lastPos);
            System.out.println(fp);
            }    
        
        }*/  
       // in.close();
       
        //return sourceCode;
        
   // }catch(MalformedURLException e){
      //  System.out.println("Something went wrong reading URL");
   // }
     //   catch(IOException e){
         //   System.out.println("hello");
        
        
      
    //catch(MalFormedURLException e){
        //System.out.println("MalFormed URL");
    //}

    //return null;           
       // newname.setText(sourceCode);
          /* String abc="<html>";
       String pqr="<marquee>";
         rss1.setText(jobs[2]);
         rss2.setText(jobs[3]);
         rss3.setText(jobs[4]);
         rss4.setText(jobs[5]);
         rss5.setText(jobs[6]);
         rss6.setText(jobs[7]);
         rss7.setText(jobs[8]);
         rss8.setText(jobs[9]);
         rss9.setText(jobs[10]);
         rss10.setText(jobs[11]);
         rss11.setText(jobs[12]);
         rss12.setText(jobs[13]);
         pqr=pqr+"</marquee>";
         abc=abc+"</html>";*/
      //  DefaultCaret caret = (DefaultCaret)newname.getCaret();
//caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
//JScrollPane scrollPane = new JScrollPane();

//scrollPane.setViewportView(newname);
//scrollPane.set
    }//GEN-LAST:event_newsActionPerformed
   
   
            



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
             //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
System.out.println(readRss("http://www.careerbuilder.com/RTQ/rss20.aspx?rssid=RSS_PD&num=25&geoip=false&ddcompany=false&ddtitle=false&cat=JN004"));

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);

            }
        });

    }
   // public javax.swing.JLabel;
    public static javax.swing.JTextField qualification1;
    public static javax.swing.JTextField research1;
    
    public static javax.swing.JTextField phone1;
    public static javax.swing.JTextField username;
    //public javax.swing.JLabel jLabel1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LINK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton login;
    private javax.swing.JTextArea newname;
    private javax.swing.JButton news;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
