package automaticpaper;

import static automaticpaper.rssFeeder.readRss;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.*;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.text.DefaultCaret;

public class Login1_1 extends javax.swing.JFrame {
public static String username1;
 public static String sourceCode="";
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    static String pwd=null;
    public static String uname = null;
    public static String[] jobs = null;
    //String user1=null;
    //private jframe frame;
    //  private Login1 frame;

    /**
     *
     */
    public Login1_1() {
         setLayout(new BorderLayout());
	setContentPane(new JLabel(new ImageIcon("C://Users//prathamesh//Desktop/1.jpg")));
	setLayout(new FlowLayout());

        initComponents();
        //jLabel6.setForeground(Color.blue);
        
        //this.setLocation(500,500);
       /* Random gen = new Random();

        Color color = new Color(gen.nextInt(240), gen.nextInt(240),
                gen.nextInt(240));
        this.getContentPane().setBackground(color);*/
        this.setTitle("LOGIN");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void close() {
        WindowEvent WinClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WinClosingEvent);
    }

    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        news = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rss7 = new javax.swing.JLabel();
        rss6 = new javax.swing.JLabel();
        rss10 = new javax.swing.JLabel();
        rss11 = new javax.swing.JLabel();
        rss4 = new javax.swing.JLabel();
        rss12 = new javax.swing.JLabel();
        rss5 = new javax.swing.JLabel();
        rss2 = new javax.swing.JLabel();
        rss3 = new javax.swing.JLabel();
        rss1 = new javax.swing.JLabel();
        rss9 = new javax.swing.JLabel();
        rss8 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlDkShadow);
        setBounds(new java.awt.Rectangle(50, 100, 400, 100));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");

        news.setText("Feeds");
        news.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:"); // NOI18N

        jLabel2.setText("password:");

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        login.setText("LogIn");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        register.setText("New User");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(login)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(txt_username))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(register)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login)
                    .addComponent(register))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        rss7.setText("jLabel5");

        rss6.setText("jLabel11");

        rss10.setText("jLabel9");

        rss11.setText("jLabel10");

        rss4.setText("jLabel9");

        rss12.setText("jLabel11");

        rss5.setText("jLabel10");

        rss2.setText("jLabel7");

        rss3.setText("jLabel8");

        rss1.setText("jLabel5");

        rss9.setText("jLabel8");

        rss8.setText("jLabel7");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rss5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rss2)
                        .addComponent(rss1)
                        .addComponent(rss3)
                        .addComponent(rss4))
                    .addComponent(rss6)
                    .addComponent(rss7)
                    .addComponent(rss8)
                    .addComponent(rss9)
                    .addComponent(rss10)
                    .addComponent(rss11)
                    .addComponent(rss12))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(rss1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rss12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1849, Short.MAX_VALUE)
                        .addGap(430, 430, 430))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(594, 594, 594)
                                .addComponent(jLabel4))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(828, 828, 828)
                .addComponent(news)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(news)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code her
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csv_db", "root", "");
            
            //frame= new Login1();
        } catch (SQLException ex) {
            Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened

    @SuppressWarnings("empty-statement")
    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
    }//GEN-LAST:event_loginMouseClicked

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        String sql = "select * from login where username=? AND Password=?";
       
        // TODO add your handling code here:
        try {

            pst = con.prepareStatement(sql);
                // pst = con.prepareStatement(sql1);
            pst.setString(1, txt_username.getText());
            pst.setString(2, txt_password.getText());
            rs = pst.executeQuery();
            pwd=txt_password.getText();
            int count = 0;
           // System.out.println(sql1);
            uname = txt_username.getText();
            //System.out.println(user);
            String password=txt_password.getText();
                    //composer4.username1=user;
            //GlobalVars.addValuesToGlobalMap("username", user);

            if (rs.next()) {
                // System.out.println(count);
                // count=count+1;
                //System.out.println(count);

             //   JOptionPane.showMessageDialog(null, "username and password is correct");
                // frame.dispose();
                // System.out.println(count);
                //frame.dispose();
                this.dispose();

                composer4 c = new composer4();
                c.setVisible(true);

                //Paper_info s= new Paper_info();
                //s.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Invalid username and password");
            }
            register r = new register();
           // Profile profile = new Profile();
           // Profile.name.setText("ABC");
          // Profile.name.setEnabled(false);
//          Profile.qualification.setText(this.qualification1.getText());
           // Profile.qualification.setEnabled(true);
//            Profile.phone.setText(this.phone1.getText());
           // Profile.phone.setEnabled(true);
            //        Profile.research.setText(this.research1.getText());
           // Profile.research.setEnabled(true);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        register register = new register();
        register.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerActionPerformed
//public static String readRss(String urlAddress) throws IOException {
     
 //   }
    private void newsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsActionPerformed
           try{
        URL rssUrl=new URL("http://www.careerbuilder.com/RTQ/rss20.aspx?rssid=RSS_PD&num=25&geoip=false&ddcompany=false&ddtitle=false&cat=JN004");
        BufferedReader in=new BufferedReader(new InputStreamReader(rssUrl.openStream()));
       
        String line;
        while ((line = in.readLine()) != null) {
    int titleEndIndex = 0;
    int titleStartIndex = 0;
    
    while (titleStartIndex >= 0) {
        titleStartIndex = line.indexOf("<title>", titleEndIndex);
        if (titleStartIndex >= 0) {
            titleEndIndex = line.indexOf("</title>", titleStartIndex);
            sourceCode += line.substring(titleStartIndex + "<title>".length(), titleEndIndex) + ",";
           
          
           // newname.setText(sourceCode);
        }
    }
}
        
           if (sourceCode.contains(",")) {
                    jobs = sourceCode.split(",");
        }
       
        System.out.println(jobs.length);
        for(int i=2;i<jobs.length;i++){
         System.out.println(jobs[i]);
        
        }
       /* while((line = in.readLine())!= null)
        {
            
            if(line.contains("<title>"))
            {
            int firstPos = line.indexOf("<title>");
            String temp = line.substring(firstPos);
            temp = temp.replace("<title>", "");
            int lastPos = temp.indexOf("</title>");
            temp = temp.substring(0, lastPos);
            sourceCode += temp+"\n";
            }
        }*/
        
       /* while((line = in.readLine())!= null)
        {
            if(line.contains("<title>"))
            {
                
                int firstPos = line.indexOf("<title>");
                String temp = line.substring(firstPos);
                int fp = temp.indexOf("</title>");
                int lastPos = line.indexOf("</title>");
                
            System.out.println(firstPos);
            System.out.println(lastPos);
            System.out.println(fp);
            }    
        
        }*/  
        in.close();
       
        //return sourceCode;
        
    }catch(MalformedURLException e){
        System.out.println("Something went wrong reading URL");
    }
        catch(IOException e){
            System.out.println("hello");
        }
        
      
    //catch(MalFormedURLException e){
        //System.out.println("MalFormed URL");
    //}

    //return null;           
       // newname.setText(sourceCode);
           
         rss1.setText(jobs[2]);
         rss2.setText(jobs[3]);
         rss3.setText(jobs[4]);
         rss4.setText(jobs[5]);
         rss5.setText(jobs[6]);
         rss6.setText(jobs[7]);
         rss7.setText(jobs[8]);
         rss8.setText(jobs[9]);
         rss9.setText(jobs[10]);
         rss10.setText(jobs[11]);
         rss11.setText(jobs[12]);
         rss12.setText(jobs[13]);
      //  DefaultCaret caret = (DefaultCaret)newname.getCaret();
//caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
//JScrollPane scrollPane = new JScrollPane();

//scrollPane.setViewportView(newname);
//scrollPane.set
    }//GEN-LAST:event_newsActionPerformed
   
   
            



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }*/
             UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
System.out.println(readRss("http://www.careerbuilder.com/RTQ/rss20.aspx?rssid=RSS_PD&num=25&geoip=false&ddcompany=false&ddtitle=false&cat=JN004"));
System.out.println("******");

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login1().setVisible(true);
                
            }
        });

    }
    
    public static javax.swing.JTextField qualification1;
    public static javax.swing.JTextField research1;
    public static javax.swing.JTextField phone1;
    public static javax.swing.JTextField username;
    //public javax.swing.JLabel jLabel1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JButton news;
    private javax.swing.JButton register;
    private javax.swing.JLabel rss1;
    private javax.swing.JLabel rss10;
    private javax.swing.JLabel rss11;
    private javax.swing.JLabel rss12;
    private javax.swing.JLabel rss2;
    private javax.swing.JLabel rss3;
    private javax.swing.JLabel rss4;
    private javax.swing.JLabel rss5;
    private javax.swing.JLabel rss6;
    private javax.swing.JLabel rss7;
    private javax.swing.JLabel rss8;
    private javax.swing.JLabel rss9;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
