/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package automaticpaper;

import java.io.File;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
//import javax.swing.UIManager;

/**
 *
 * @author Admin
 */
public class Mail extends javax.swing.JFrame {

    /**
     * Creates new form Mail
     */
    public Mail() {
        setContentPane(new JLabel(new ImageIcon("C://Users//Joyan//Desktop//11.jpg")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        fromtext = new javax.swing.JTextField();
        to = new javax.swing.JLabel();
        subjecttext = new javax.swing.JTextField();
        subject = new javax.swing.JLabel();
        content = new javax.swing.JTextField();
        totext = new javax.swing.JTextField();
        mail1 = new javax.swing.JButton();
        attach = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        back1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 0, 400, 100));
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 20, 919, 65);

        from.setText("FROM");
        getContentPane().add(from);
        from.setBounds(161, 195, 68, 35);

        fromtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromtextActionPerformed(evt);
            }
        });
        getContentPane().add(fromtext);
        fromtext.setBounds(239, 195, 382, 35);

        to.setText("TO");
        getContentPane().add(to);
        to.setBounds(161, 249, 68, 32);
        getContentPane().add(subjecttext);
        subjecttext.setBounds(239, 296, 382, 35);

        subject.setText("SUBJECT");
        getContentPane().add(subject);
        subject.setBounds(161, 294, 68, 38);

        content.setOpaque(false);
        getContentPane().add(content);
        content.setBounds(239, 350, 681, 171);

        totext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totextActionPerformed(evt);
            }
        });
        getContentPane().add(totext);
        totext.setBounds(239, 248, 382, 35);

        mail1.setText("MAIL");
        mail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail1ActionPerformed(evt);
            }
        });
        getContentPane().add(mail1);
        mail1.setBounds(239, 539, 91, 28);

        attach.setText("Attach File");
        attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachActionPerformed(evt);
            }
        });
        getContentPane().add(attach);
        attach.setBounds(348, 539, 102, 28);
        getContentPane().add(path);
        path.setBounds(460, 539, 383, 33);

        back1.setText("BACK");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        getContentPane().add(back1);
        back1.setBounds(767, 119, 59, 33);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\images.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 250, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totextActionPerformed

    private void mail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail1ActionPerformed
       // String From=fromtext.getText();
        String From="cccaaa154@gmail.com";
        fromtext.setText("cccaaa154@gmail.com");
       String To=totext.getText();
        String Subject1=subjecttext.getText();
        String Content=content.getText();
        
        Properties prop=new Properties();
       prop.put("mail.smtp.host","smtp.gmail.com");
       prop.put("mail.smtp.socketFactory.port","465");
       prop.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
       prop.put("mail.smtp.auth","true");
       prop.put("mail.smtp.port","465");
       Session session= Session.getDefaultInstance(prop,
               
               new javax.mail.Authenticator() {
                 protected PasswordAuthentication getPasswordAuthentication(){
                     return new PasswordAuthentication("cccaaa154@gmail.com","");
                     
                 }
               }
               
               );
       try
       {
           Message message=new MimeMessage(session);
           message.setFrom(new InternetAddress(From));
           message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(To));
           message.setSubject(Subject1);
           MimeBodyPart messagebodypart=new MimeBodyPart();
           messagebodypart.setText(Content);
           Multipart multipart=new MimeMultipart();
           multipart.addBodyPart(messagebodypart);
           messagebodypart=new MimeBodyPart();
           javax.activation.DataSource source=new FileDataSource(attachment);
           messagebodypart.setDataHandler(new DataHandler(source));
           messagebodypart.setFileName(attach.getText());
           multipart.addBodyPart(messagebodypart);
           message.setContent(multipart);
           
           //message.setText(Content);
           Transport.send(message);
           JOptionPane.showMessageDialog(null,"Message Sent");
       }catch(Exception e){
          // throw new RuntimeException(e);
        JOptionPane.showMessageDialog(null,e);
       }
       
    }//GEN-LAST:event_mail1ActionPerformed

    private void attachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachActionPerformed
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        attachment=f.getAbsolutePath();
        path.setText(attachment);
    
    }//GEN-LAST:event_attachActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        composer4 c=new composer4();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back1ActionPerformed

    private void fromtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromtextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       /* try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
         //   UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mail().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attach;
    private javax.swing.JButton back1;
    private javax.swing.JTextField content;
    private javax.swing.JLabel from;
    public javax.swing.JTextField fromtext;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton mail1;
    private javax.swing.JTextField path;
    private javax.swing.JLabel subject;
    private javax.swing.JTextField subjecttext;
    private javax.swing.JLabel to;
    private javax.swing.JTextField totext;
    // End of variables declaration//GEN-END:variables
 String attachment;
}
