/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package automaticpaper;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author Omkar Joshi <omkar.joshi@truprogresstech.in>
 */
public class Profile extends javax.swing.JFrame {
    public static String username1;
     Connection con = null;
      PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Profile
     */
    public Profile() {
        setContentPane(new JLabel(new ImageIcon("C://Users//Joyan//Desktop//11.jpg")));
        initComponents();
         Random gen = new Random();
         

       /* Color color = new Color(gen.nextInt(240), gen.nextInt(240),
                gen.nextInt(240));
        this.getContentPane().setBackground(color);*/
        this.setTitle("PROFILE");
       // this.name.setText(GlobalVars.getGlobalMap().get("a"));
       // this.research.setText(GlobalVars.getGlobalMap().get("b"));
       // this.phone.setText(GlobalVars.getGlobalMap().get("c"));
       // this.qualification1.setText(GlobalVars.getGlobalMap().get("d"));
        
        
    }
    
    public void execute()  throws ClassNotFoundException, InstantiationException, IllegalAccessException, IOException
    {
                 try {
           Connection con = null;
  PreparedStatement pst = null;
    ResultSet rs = null;
     String uname1=Login1.uname;
           
       con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csv_db", "root", "");
       Statement s=con.createStatement();
       Class.forName("com.mysql.jdbc.Driver").newInstance();
      String sql1="select username,Research,Phone,Qualification,Image from login where username='"+uname1+"'";
       pst = con.prepareStatement(sql1);
       rs = pst.executeQuery();
       String research1=null;
       String phone1=null;
       String qual1=null;
       String name1=null;
       
       while (rs.next()) {
       research1 = rs.getString("Research");
       phone1 = rs.getString("Phone");
       qual1 = rs.getString("Qualification");
       name1 = rs.getString("username");
       BufferedImage im = ImageIO.read(rs.getBinaryStream("Image"));
         image.setIcon(new ImageIcon(im));
       
       }
       System.out.println(name1);
       System.out.println(research1);
       System.out.println(phone1);
       System.out.println(qual1);
       
       name.setText(name1);
       qualification1.setText(qual1);
       research.setText(research1);
       phone.setText(phone1);
     //  GlobalVars.addValuesToGlobalMap("a", name);
     //  GlobalVars.addValuesToGlobalMap("c", phone);
     //  GlobalVars.addValuesToGlobalMap("d", qual);
      // GlobalVars.addValuesToGlobalMap("b", research);

       
        
     }  catch (SQLException ex) {
            Logger.getLogger(Pass.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        try {
            /*
            // TODO add your handling code here:
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csv_db", "root", "");
           String sql1 = "SELECT Research,Phone,Qualification from login where username=Aniruddha Narendra Joshi";
          //  String sql1 = null;
            pst=con.prepareStatement(sql1);
               rs = pst.executeQuery();
               System.out.println(sql1);
            //frame= new Login1();*/
        } catch (Exception ex) {
            Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }

   
    
    }                                 

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        qualification = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        research = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        qualification1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 0, 400, 100));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        image.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.add(image);
        image.setBounds(60, 20, 168, 172);

        jLabel1.setText("Research Interest:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(23, 274, 120, 27);

        jLabel3.setText("Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(23, 248, 70, 14);

        jLabel6.setText("Phone Number:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(23, 319, 90, 14);

        jLabel8.setText("Qualification:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(23, 364, 80, 14);
        jPanel1.add(qualification);
        qualification.setBounds(133, 346, 0, 0);
        jPanel1.add(name);
        name.setBounds(150, 240, 190, 20);

        research.setText("reasearch");
        jPanel1.add(research);
        research.setBounds(150, 280, 170, 14);

        phone.setText("phone");
        jPanel1.add(phone);
        phone.setBounds(150, 320, 80, 14);

        qualification1.setText("qualification");
        jPanel1.add(qualification1);
        qualification1.setBounds(150, 360, 110, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 240, 363, 423);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(190, 10, 1088, 65);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1000, 110, 59, 34);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\images.jpg")); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 250, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        composer4 c=new composer4();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            
            }
            // UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    public static javax.swing.JLabel qualification;
    private javax.swing.JLabel qualification1;
    private javax.swing.JLabel research;
    // End of variables declaration//GEN-END:variables
}
