/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package automaticpaper;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import automaticpaper.Login1;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Omkar Joshi <omkar.joshi@truprogresstech.in>
 */
public class register extends javax.swing.JFrame {
Connection con = null;
  PreparedStatement pst = null;
    ResultSet rs = null;
    String path=null;
    /**
     * Creates new form register
     */
    public register() {
        setContentPane(new JLabel(new ImageIcon("C://Users//Joyan//Desktop//11.jpg")));
        initComponents();
      // setContentPane(new JLabel(new ImageIcon("C://Users//Admin//Downloads/11.jpg")));
       this.setSize(1130,725);
         //Random gen = new Random();

        /*Color color = new Color(gen.nextInt(256), gen.nextInt(256),
                gen.nextInt(256));
        this.getContentPane().setBackground(color);*/
        this.setTitle("REGISTER");
        
    }
     public void close() {
        WindowEvent WinClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(WinClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        uu = new javax.swing.JLabel();
        ee = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        pp = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        rpassword = new javax.swing.JTextField();
        Account = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        research1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phone1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qualification1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        image = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(100, 0, 400, 100));
        setResizable(false);
        getContentPane().setLayout(null);

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1030, 90, 71, 36);

        jPanel1.setOpaque(false);

        uu.setText("Username");

        ee.setText("Email ID");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        pp.setText("Password");

        rr.setText("Re-type Password");

        Account.setText("Create Account");
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });

        jLabel1.setText("Research Interest");

        research1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                research1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Phone Number");

        phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Qualification");

        qualification1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualification1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pp)
                    .addComponent(ee)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(Account)
                            .addComponent(rr))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rpassword)
                            .addComponent(email)
                            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(password)
                            .addComponent(research1)
                            .addComponent(phone1)
                            .addComponent(qualification1))))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(uu)
                    .addContainerGap(376, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ee))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pp))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rr))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(research1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qualification1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Account)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(uu)
                    .addContainerGap(345, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 260, 434, 370);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("ADVANCE QUESTION PAPER GENERATION SYSTEM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 0, 919, 65);

        jButton1.setText("UPLOAD PHOTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 490, 138, 40);
        getContentPane().add(image);
        image.setBounds(570, 240, 163, 204);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\images.jpg")); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 0, 230, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        try {
            // TODO add your handling code here:
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csv_db", "root", "");
            
            //frame= new Login1();
        } catch (SQLException ex) {
          //  Logger.getLogger(Login1.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }                                 
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       this.dispose();
       Login1 l=new Login1();
       l.setVisible(true);
      //  Login1 login=new Login1();
//        login.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed
String username2,email2,password2,password1,retype2,research2,phone2,quali2;
    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
   
   username2=username.getText();
   email2=email.getText();
   password1=password.getText();
   password2=rpassword.getText();
   research2=research1.getText();
   phone2=phone1.getText();
   quali2=qualification1.getText();
           
       //String sql = "Insert into login(username,Email_ID,Password,Retype_Password,Research,Phone,Qualification,Image) values('"+username.getText()+"','"+email.getText()+"','"+password.getText()+"','"+rpassword.getText()+"','"+research1.getText()+"','"+phone1.getText()+"','"+qualification1.getText()+",?)";
     
  //String sql = "Insert into login(username,Email_ID,Password,Retype_Password,Research,Phone,Qualification) values(username2,email12,password1,password2,research2,phone2,quali2)";

        
       try {
           
       con = DriverManager.getConnection("jdbc:mysql://localhost:3306/csv_db", "root", "");
       Statement s=con.createStatement();
       //s.executeUpdate(sql);
       
       FileInputStream fis;
           
// Load JDBC driver "com.mysql.jdbc.Driver"
Class.forName("com.mysql.jdbc.Driver").newInstance();
/* Create a connection by using getConnection() method that takes 
parameters of string type connection url, user name and password to 
connect to database. */
//con= DriverManager.getConnection(connectionURL, "root", "");
// create a file object for image by specifying full path of image as parameter.
File image = new File(path);
/* prepareStatement() is used for create statement object that is 
used for sending sql statements to the specified database. */
pst = con.prepareStatement
("insert into login(username,Email_ID,Password,Retype_Password,Research,Phone,Qualification,Image)"+ "values(?,?,?,?,?,?,?,?)");
pst.setString(1,username.getText());
pst.setString(2,email.getText());
pst.setString(3,password.getText());
pst.setString(4,rpassword.getText());
pst.setString(5,research1.getText());
pst.setString(6,phone1.getText());
pst.setString(7,qualification1.getText());

fis = new FileInputStream(image);
pst.setBinaryStream(8, (InputStream)fis, (int)(image.length()));
/* executeUpdate() method execute specified sql query. Here this query 
insert data and image from specified address. */ 
int s1 = pst.executeUpdate();
if(s1>0) {
System.out.println("Uploaded successfully !");
}
else {
System.out.println("unsucessfull to upload image.");
}
}
// catch if found any exception during rum time.
catch (Exception ex) {
System.out.println("Found some error : "+ex);
}
/*catch (SQLException ex) {
        Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
 }*/
finally {
       try {
           // close all the connections.
           con.close();
           pst.close();
       } catch (SQLException ex) {
           Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
       }

}
       
      //  pst=con.prepareStatement(sql);
     
       /* pst.setString(1,username.getText());
        pst.setString(2,email.getText());
      //  System.out.println("1");
        pst.setString(3,password.getText());
        pst.setString(4,rpassword.getText());
          pst.setString(5,research1.getText());
            pst.setString(6,phone1.getText());
              pst.setString(7,qualification1.getText());*/
             //rs = pst.executeQuery();
        /*if(rs.next())
        {
        JOptionPane.showMessageDialog(null,"saved");
        }
        else
        {
             JOptionPane.showMessageDialog(null,"not saved");
        }*/
        
    
        this.dispose();
        Login1 login=new Login1();
        login.setVisible(true);
       
    }//GEN-LAST:event_AccountActionPerformed
     
    private void research1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_research1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_research1ActionPerformed

    private void qualification1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualification1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualification1ActionPerformed

    private void phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JFileChooser filechooser= new JFileChooser();
    filechooser.setDialogTitle("Choose Your File");
    filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    //below codes for select  the file 
    int returnval=filechooser.showOpenDialog(this);
    if(returnval==JFileChooser.APPROVE_OPTION)
    {
        File file = filechooser.getSelectedFile();
        BufferedImage bi;
        try
        {   path=file.getAbsolutePath();
            //display the image in jlabel
            bi=ImageIO.read(file);
            image.setIcon(new ImageIcon(bi));
        }
        catch(IOException e)
        {

        }
        this.pack();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
          //  UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JButton back;
    private javax.swing.JLabel ee;
    private javax.swing.JTextField email;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField password;
    public static javax.swing.JTextField phone1;
    private javax.swing.JLabel pp;
    public static javax.swing.JTextField qualification1;
    public static javax.swing.JTextField research1;
    private javax.swing.JTextField rpassword;
    private javax.swing.JLabel rr;
    public static javax.swing.JTextField username;
    private javax.swing.JLabel uu;
    // End of variables declaration//GEN-END:variables
}
